version: '3'
services:
  vlib_db:
    image: postgres
    restart: always
    ports:
        - 5000:5432
    environment:
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: vlib_db
  adminer:
    image: adminer
    restart: always
    ports:
      - 5001:8080