server:
  port: 8181
  servlet:
    context-path: /vlib

spring:
  application:
    name: video-lib
  datasource:
    url: jdbc:postgresql://ec2-34-225-162-157.compute-1.amazonaws.com:5432/d2q7onkrfthu7j
    username: vwozgpvjclthjg
    password: cde17aaa8e46d1cdda23ea310de61e3dd4586df8999818822928f24b522670d4
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 5014057553-8gm9um6vnli3cle5rgigcdjpdrid14m9.apps.googleusercontent.com
            clientSecret: tWZKVLxaD_ARWsriiiUFYoIk
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile

vlib:
  jwt:
    expire: 60
    signing:
      key: 926D96C90030DD58429D2751AC1BDBBC
  oAuth2:
    authorizedRedirectURIs: http://localhost:4200/oauth2/redirect

logging:
  file:
    path: ${user.home}/logs