spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5000/vlib_db
    username: postgres
    password: admin
    initialization-mode: always
#    data: classpath:db/misc/truncate_tables.sql,classpath:db/misc/data.sql
  jpa:
    ddl-auto: update
    show-sql: true