spring:
  datasource:
    url: jdbc:postgresql://192.168.99.100:5000/vlib_db
    username: postgres
    password: admin
    initialization-mode: always
    data: classpath:db/data/truncate_tables.sql,classpath:db/data/V2020_12_14__data_category.sql
  jpa:
    ddl-auto: update
    show-sql: true